default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ahiru154@
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: menu_app_development

test:
  <<: *default
  database: menu_app_test

production:
  <<: *default
  database:  menu_app
  username: production_username
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
