@startuml

entity "ユーザー" {
  *ユーザーID
  ---
  -ログインID
  -パスワード(ハッシュ)
  -ユーザー名
  -プロフィール画像
}

entity "レシピ" {
  *レシピID
  ---
  *ユーザーID<<FK>>
  -レシピ名
  -レシピ画像
}

entity "食材" {
  *食材ID
  ---
  *レシピID<<FK>>
  -食材名
}

entity "レシピ食材" {
  ---
  *レシピID<<FK>>
  *食材ID<<FK>>
}


"ユーザー" ||--o{ "レシピ"
"レシピ" }o--|| "レシピ食材"
"食材" }o--|| "レシピ食材"

@enduml