@startuml

entity "ユーザー" {
  *ユーザーID
  ---
  -ログインID
  -パスワード(ハッシュ)
  -ユーザー名
  -プロフィール画像
}

entity "レシピ" {
  *レシピID
  ---
  *ユーザーID<<FK>>
  -レシピ名
  -レシピ画像
}

entity "食材" {
  *食材ID
  ---
  *レシピID<<FK>>
  -食材名
}


"ユーザー" ||--o{ "レシピ"
"レシピ" ||--o{ "食材"

@enduml